[package]
name = "egui-image-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"
egui = "0.30.0"
egui_extras = "0.30.0"
image = "0.25.5"

[lints.clippy]
int_plus_one = { level = "allow"}
